title: Shafqat Ehsan
email: sfehsan@mdanderson.org
description: >- # this means to ignore newlines until "baseurl:"
  Science is a way of thinking more than it is a body of knowledge 
                                                    -Carl Sagan
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ScientificEhsan  
github_username:  ScientificEhsan
linkedin_username: Shafqatehsan

remote_theme: mmistakes/minimal-mistakes@4.24.0 
plugins:
  - jekyll-feed 
