title: Shafqat Ehsan
email: sfehsan@mdanderson.org
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
theme: minima
plugins:
  - jekyll-feed
